[dev]
   command = "npm run dev"
[build]
  command = "npm run generate"
  publish = "dist"
  functions = 'functions'
[[redirects]]
   from= "/api/*"
   to = "/.netlify/functions/:splat"
   status = 200
[[headers]]
   for = "/api/*"
   Access-Control-Allow-Origin = "https://clipsy.xyz"